version: '3.8'

services:
  # Message Broker
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  # Databases
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  postgresql:
    image: postgres:13
    environment:
      POSTGRES_DB: webcrawler
      POSTGRES_USER: crawler
      POSTGRES_PASSWORD: crawler123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  # Web Crawler Services
  url-frontier:
    build: ./services/url-frontier
    depends_on:
      - kafka
      - redis
      - postgresql
    environment:
      - KAFKA_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://crawler:crawler123@postgresql:5432/webcrawler
    volumes:
      - ./services/url-frontier:/app

  url-scheduler:
    build: ./services/url-scheduler
    depends_on:
      - kafka
      - redis
      - url-frontier
    environment:
      - KAFKA_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./services/url-scheduler:/app

  # Fetcher Shards (Horizontally Scalable)
  fetcher-shard-0:
    build: ./services/fetcher
    depends_on:
      - kafka
      - redis
      - url-scheduler
    environment:
      - FETCHER_SHARD_ID=0
      - KAFKA_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - CONCURRENT_REQUESTS=20
      - FETCH_BATCH_SIZE=10
    volumes:
      - ./services/fetcher:/app

  fetcher-shard-1:
    build: ./services/fetcher
    depends_on:
      - kafka
      - redis
      - url-scheduler
    environment:
      - FETCHER_SHARD_ID=1
      - KAFKA_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - CONCURRENT_REQUESTS=20
      - FETCH_BATCH_SIZE=10
    volumes:
      - ./services/fetcher:/app

  fetcher-shard-2:
    build: ./services/fetcher
    depends_on:
      - kafka
      - redis
      - url-scheduler
    environment:
      - FETCHER_SHARD_ID=2
      - KAFKA_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - CONCURRENT_REQUESTS=20
      - FETCH_BATCH_SIZE=10
    volumes:
      - ./services/fetcher:/app

  fetcher-shard-3:
    build: ./services/fetcher
    depends_on:
      - kafka
      - redis
      - url-scheduler
    environment:
      - FETCHER_SHARD_ID=3
      - KAFKA_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - CONCURRENT_REQUESTS=20
      - FETCH_BATCH_SIZE=10
    volumes:
      - ./services/fetcher:/app

  # Parser Service
  parser:
    build: ./services/parser
    depends_on:
      - kafka
      - redis
      - fetcher-shard-0
      - fetcher-shard-1
      - fetcher-shard-2
      - fetcher-shard-3
    environment:
      - KAFKA_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - PROCESSING_BATCH_SIZE=10
      - MIN_CONTENT_LENGTH=100
    volumes:
      - ./services/parser:/app

  # Content Indexer Service
  indexer:
    build: ./services/indexer
    container_name: webcrawler_indexer
    environment:
      - KAFKA_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - PROCESSING_BATCH_SIZE=10
      - BULK_INDEX_SIZE=100
    depends_on:
      - kafka
      - redis
      - elasticsearch
      - parser
    networks:
      - webcrawler_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Search API Service
  search-api:
    build: ./services/search-api
    container_name: webcrawler_search_api
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - redis
      - indexer
    networks:
      - webcrawler_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
  postgres_data:
  elasticsearch_data: 